### ISSUE TITLE
Capture Barcode Image 

### ISSUE THREAD

**Issue by mahmoud-elnaggar** [LivotovLabs/zxscanlib#26]
I want to save barcode image after I get data from image 
I tried 
Bitmap temp = Bitmap.createBitmap(barcodeView.getWidth(), barcodeView.getHeight(), Bitmap.Config.ARGB_8888);
Canvas canvas = new Canvas(temp);
barcodeView.getCamera().draw(canvas);
but the image is black with red HUD.
Thanks for your helpful lib

**Comment by aaronbond** [comment]
depending on your needs perhaps it would be better to use a qr generating library to generate a new one from the data you pulled in.

**Comment by mahmoud-elnaggar** [comment]
No I want to save all image not barcode only 
say I read any product's Barcode  so I want to save camera frame

**Comment by aaronbond** [comment]
i haven't looked into it but that would probably require editing the code in this project to provide that kind of functionality (saving the frame before it's thrown away)

**Comment by livotov** [comment]
your code above grabs the ScanView layout image. But camera streams its data using the SurfaceView object, that's why you don't see the actual camera image.

You can override ScannerView.public void onPreviewData(final byte[] bytes, final int i, final Camera.Size size) method to use the camera image. Please note, that camera frame byte array is not an RGB but YUV one.
