### ISSUE TITLE
Build failed when adding zxscanlib

### ISSUE THREAD

**Issue by tryadelion** [LivotovLabs/zxscanlib#29]
hello, i'm replacing an outdated library in my app with zxscanlib, in a clean environement works perfectly, but when added, gives many build errors, do you use any library that could cause file conflict? most errors come from .xml  SRC files. 

tried with different versions, 2.00, 2.0.1, 2.1.0 snapshot... all give the same errors.

example ( there are 66 more).

AGPBI: {"kind":"ERROR","text":"Attribute \"textAppearanceListItemSmall\" has already been defined","sourcePath":"/PROJECT_PATH/app/build/intermediates/exploded-aar/eu.livotov.labs/zxscanlib/2.1.0-SNAPSHOT/res/values/values.xml","position":{"startLine":1},"original":""}

**Comment by livotov** [comment]
Hi, that's strange. zxscanlib does not use any other deps rather than CAMView which does not use deps at all. There were several old unused string and color resources there, however, but have no idea how they can cause such conflicts. 

Anyway, deleted them, so please try 2.1.1 snapshot, once it is available (see version number changes in readme.md)

**Comment by tryadelion** [comment]
just wanted to say thanks, the 2.1.1 snapshot also fixed performance issues when stopping the camera, so this update fixed all my problems.
